### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by frederic-santos**
Fixed typo in `ob-julia.el`

### CODE REVIEW

**Comment by nico202** [comment]
Thanks, sorry for the delay, but I have a new and better version of this repo, I need to write documentation and publish it, so this is abandoned.  If you are interested in ob-julia, I'll ping you when I'll release this new version :)

**Comment by frederic-santos** [comment]
Thanks, it would be great!

P.-S.: there is [at least one other person](https://github.com/vincent-picaud/Julia_with_OrgMode_Example) who is currently working on ob-julia. Since I'm still a beginner in both Julia and Elisp, I'm not sure I can really help for the code part. But if I can be of any help for one or both of you (for the documentation part or something else), I would be glad to try!

**Comment by nico202** [comment]
Thanks, the repo is [here](https://git.nixo.xyz/nixo/ob-julia)

The aim was to support async evaluation, figures and other julia package without requiring them (if they are available, they are used).  You can have a look at the repo

**Comment by non-Jedi** [comment]
@nico202 do you intend to maintain and take bug reports on [your ob-julia](https://git.nixo.xyz/nixo/ob-julia)? If so, where should patches and bugs be sent? Or have you intentionally not created a way of doing such until you consider the package ready for release.

**Comment by frederic-santos** [comment]
Yep, it was me ;)
I really appreciate @nico202 effort to create and maintain this package. However, I do have some bugs and problems with the current version of `ob-julia`. Would be nice to report them, indeed. Also, if you need/want help for this project, you might find some folks on Julia discourse.

**Pull request merged**
